name: Deploy to GoDaddy Server

on:
  push:
    branches:
      - main # Adjust the branch name as per your requirements

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH keys
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GoDaddy
        run: |
           ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /home/aqyxflpn4rpk/Applications/MyProfileConnectBackend && git pull"

